# Generated by Django 4.2.5 on 2023-11-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='assignedDoctor',
            new_name='assignedDoctorID',
        ),
    ]
