# Generated by Django 4.2.5 on 2023-11-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_assigneddoctor_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorName',
            new_name='doctorID',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientName',
            new_name='patientID',
        ),
    ]
