# Generated by Django 4.2.5 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_rename_doctorname_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
